ignoredBuiltDependencies:
  - sharp
  - unrs-resolver

overrides:
  next@>=15.0.0 <15.1.6: '>=15.1.6'
  next@>=15.0.0 <15.2.2: '>=15.2.2'
  next@>=15.0.4-canary.51 <15.1.8: '>=15.1.8'
  next@>=15.0.0 <15.2.3: '>=15.2.3'
