#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

pnpm lint
pnpm types
pnpm format
pnpm check:packages

if git diff --staged --quiet; then
  echo "No changes to commit after formatting."
  exit 1
fi

exit 0

